### ISSUE TITLE
[Feature Request] Run headless on a web server

### ISSUE THREAD

**Issue by RhanCandia** [Suwayomi/Suwayomi-VaadinUI#153]
Can this be ran on a web server headlessly? It looks like a desktop app but it is accessible via an address. So I got curious because it would be nice if I can host it on a webserver.

I was trying to run this on Docker but I am getting the following error:

```
vaadin-ui-vaadinui-1  | 00:53:06.647 [main] ERROR o.s.boot.SpringApplication - Application run failed
vaadin-ui-vaadinui-1  | java.lang.reflect.UndeclaredThrowableException: Failed to invoke event listener method
vaadin-ui-vaadinui-1  | HandlerMethod details:
vaadin-ui-vaadinui-1  | Bean [online.hatsunemiku.tachideskvaadinui.startup.TrayHandler]
vaadin-ui-vaadinui-1  | Method [public void online.hatsunemiku.tachideskvaadinui.startup.TrayHandler.registerTray()]
```

And a few more. It looks like it was trying to register some components for a desktop but since I was on a web server it was failing.

Here's my Dockerfile:

```
FROM openjdk:21-jdk-slim
COPY *.jar app.jar
EXPOSE 80
ENTRYPOINT ["java", "-jar", "/app.jar", "--server.port=80"]
```

**Comment by aless2003** [comment]
As of now, no, this is intended for running on a Desktop, I however very much can make some modifications in the next update to make it detect a headless environment (and or an option, unsure yet) and just ignore all the Desktop stuff. I'll let you know when it's out though in this issue

**Comment by RhanCandia** [comment]
@aless2003 thanks!

It looks like the registerTray() can be overlooked. After that it asked for a few dependencies which I tried to install and get past further and further.

However I hit this one eventually:
```
Caused by: java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
```

It looks like it was requiring me to make sure I have a display. Now that one I don't really know if Docker is capable. So I stopped here.

Here's my updated Dockerfile for reference.
```
FROM openjdk:24-jdk-bullseye
RUN apt-get update
RUN apt-get install libxext6 libxi6 libxrender1 libxtst6 -y
COPY *.jar app.jar
EXPOSE 80
ENTRYPOINT ["java", "-jar", "/app.jar", "--server.port=80"]
```

Thanks for giving this enhancement some consideration. Have a nice day!

**Comment by aless2003** [comment]
#154 will add support for this. I modified your stuff slightly:

```dockerfile
FROM openjdk:24-jdk-bullseye
RUN apt-get update
RUN apt-get install libxext6 libxi6 libxrender1 libxtst6 -y
COPY *.jar app.jar
EXPOSE 80
EXPOSE 4567
ENTRYPOINT ["java", "-jar", "-Dvaaui.headless=true", "/app.jar", "--server.port=80"]
```

Not sure if you need that EXPOSE 4567, but it's 4am here and I'm too lazy to do it now 😅

If you want, you can just pull the branch and use ./gradlew buildReleaseJar to get a Jar so it works for you until I merged it and have a new release coming out

**Comment by aless2003** [comment]
Also note you'll have to allow it to expose 4567 since otherwise the pictures won't load, as those come from the Suwayomi Server and not my UI directly.
I usually ran my docker image like this
```
docker run -p 80:80 -p 4567:4567 test
```

**Comment by RhanCandia** [comment]
Thank you. I’ll give it a try this after work.

The reason I didn’t expose the port 4567 is becquse my suwayomi instance is also running in port 80. They are inside a private network.

I’ll let you know how it goes when I get the chance.

**Comment by RhanCandia** [comment]
Unfortunately I am limited by my environment. It won't compile on an arm64 environment. I guess I'll just wait for your build. Thanks!

```
5.210 Starting a Gradle Daemon (subsequent builds will be faster)
67.81 > Task :compileJava FAILED
67.81
67.81 FAILURE: Build failed with an exception.
67.81
67.81 * What went wrong:
67.82 Execution failed for task ':compileJava'.
67.82 > Error while evaluating property 'javaCompiler' of task ':compileJava'.
67.82    > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
67.82       > No matching toolchains found for requested specification: {languageVersion=21, vendor=BELLSOFT, implementation=vendor-specific} for LINUX on aarch64.
67.82          > No locally installed toolchains match and toolchain download repositories have not been configured.
```

**Comment by RhanCandia** [comment]
I managed to build it. I just had to switch from the openJDK image to the Bellsoft one to match the vendor. Also the version, I downgraded the image to 21.

It still won't run though.

Here's the updated Dockerfile (with the assumption it will be inside the repo):
```
FROM bellsoft/liberica-openjdk-debian:21
RUN apt-get update
RUN apt-get install libxext6 libxi6 libxrender1 libxtst6 -y
WORKDIR /app
COPY . ./
RUN chmod +x ./gradlew
RUN ./gradlew buildReleaseJar
RUN mv ./build/libs/*.jar ./build/libs/app.jar
EXPOSE 80
ENTRYPOINT ["java", "-jar", "-Dvaaui.headless=true", "-Dserver.port=80", "/app/build/libs/app.jar"]
```

Here's the error still complaining about the tray and the display:
```
vaadin-ui-vaadinui-1  | 04:22:06.218 [main] ERROR o.s.boot.SpringApplication - Application run failed
vaadin-ui-vaadinui-1  | java.lang.reflect.UndeclaredThrowableException: Failed to invoke event listener method
vaadin-ui-vaadinui-1  | HandlerMethod details:
vaadin-ui-vaadinui-1  | Bean [online.hatsunemiku.tachideskvaadinui.startup.TrayHandler]
vaadin-ui-vaadinui-1  | Method [public void online.hatsunemiku.tachideskvaadinui.startup.TrayHandler.registerTray()]
vaadin-ui-vaadinui-1  | Resolved arguments:
vaadin-ui-vaadinui-1  |
vaadin-ui-vaadinui-1  |         at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:382)
vaadin-ui-vaadinui-1  |         at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:237)
vaadin-ui-vaadinui-1  |         at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:168)
vaadin-ui-vaadinui-1  |         at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
vaadin-ui-vaadinui-1  |         at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
vaadin-ui-vaadinui-1  |         at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
vaadin-ui-vaadinui-1  |         at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451)
vaadin-ui-vaadinui-1  |         at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:103)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:76)
vaadin-ui-vaadinui-1  |         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:76)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.SpringApplication.run(SpringApplication.java:341)
vaadin-ui-vaadinui-1  |         at online.hatsunemiku.tachideskvaadinui.TachideskVaadinUiApplication.main(TachideskVaadinUiApplication.java:26)
vaadin-ui-vaadinui-1  |         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
vaadin-ui-vaadinui-1  |         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
vaadin-ui-vaadinui-1  | Caused by: java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
vaadin-ui-vaadinui-1  |         at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
vaadin-ui-vaadinui-1  |         at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:105)
vaadin-ui-vaadinui-1  |         at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
vaadin-ui-vaadinui-1  |         at java.desktop/sun.awt.X11GraphicsEnvironment.initStatic(X11GraphicsEnvironment.java:64)
vaadin-ui-vaadinui-1  |         at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:59)
vaadin-ui-vaadinui-1  |         at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:37)
vaadin-ui-vaadinui-1  |         at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:91)
vaadin-ui-vaadinui-1  |         at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:82)
vaadin-ui-vaadinui-1  |         at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:104)
vaadin-ui-vaadinui-1  |         at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:225)
vaadin-ui-vaadinui-1  |         at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:41)
vaadin-ui-vaadinui-1  |         at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:595)
vaadin-ui-vaadinui-1  |         at java.desktop/java.awt.SystemTray.isSupported(SystemTray.java:213)
vaadin-ui-vaadinui-1  |         at online.hatsunemiku.tachideskvaadinui.startup.TrayHandler.registerTray(TrayHandler.java:41)
vaadin-ui-vaadinui-1  |         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
vaadin-ui-vaadinui-1  |         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
vaadin-ui-vaadinui-1  |         at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:365)
vaadin-ui-vaadinui-1  |         ... 20 common frames omitted
vaadin-ui-vaadinui-1  | 04:22:06.222 [main] INFO  o.h.t.services.SettingsService - Saving settings
vaadin-ui-vaadinui-1  | 04:22:06.246 [main] INFO  o.h.t.startup.TachideskStarter - Stopping Jar
```

**Comment by aless2003** [comment]
It shouldn't even enter registerTray... Can you send the full log file, there should be a "Headless mode: ..." In the first couple lines. I assume that, for some reason, the headless arg isn't passed on, but need that line to confirm it

**Comment by RhanCandia** [comment]
> It shouldn't even enter registerTray... Can you send the full log file, there should be a "Headless mode: ..." In the first couple lines. I assume that, for some reason, the headless arg isn't passed on, but need that line to confirm it

The entire log:
```
vaadin-ui-vaadinui-1  | Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
vaadin-ui-vaadinui-1  |   .   ____          _            __ _ _
vaadin-ui-vaadinui-1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
vaadin-ui-vaadinui-1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
vaadin-ui-vaadinui-1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
vaadin-ui-vaadinui-1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
vaadin-ui-vaadinui-1  |  =========|_|==============|___/=/_/_/_/
vaadin-ui-vaadinui-1  |
vaadin-ui-vaadinui-1  |  :: Spring Boot ::                (v3.3.0)
vaadin-ui-vaadinui-1  |
vaadin-ui-vaadinui-1  | 09:16:45.310 [background-preinit] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 8.0.1.Final
vaadin-ui-vaadinui-1  | 09:16:45.456 [main] INFO  o.h.t.TachideskVaadinUiApplication - Starting TachideskVaadinUiApplication v1.13.0 using Java 21.0.5 with PID 1 (/app/build/libs/app.jar started by root in /app)
vaadin-ui-vaadinui-1  | 09:16:45.458 [main] INFO  o.h.t.TachideskVaadinUiApplication - No active profile set, falling back to 1 default profile: "default"
vaadin-ui-vaadinui-1  | 09:16:45.674 [main] INFO  o.s.b.d.e.DevToolsPropertyDefaultsPostProcessor - For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
vaadin-ui-vaadinui-1  | 09:16:48.445 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port 80 (http)
vaadin-ui-vaadinui-1  | 09:16:48.459 [main] INFO  o.a.coyote.http11.Http11NioProtocol - The ["http-nio-80"] connector has been configured to support HTTP upgrade to [h2c]
vaadin-ui-vaadinui-1  | 09:16:48.460 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-80"]
vaadin-ui-vaadinui-1  | 09:16:48.462 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
vaadin-ui-vaadinui-1  | 09:16:48.463 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/10.1.24]
vaadin-ui-vaadinui-1  | 09:16:48.511 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
vaadin-ui-vaadinui-1  | 09:16:48.512 [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 2837 ms
vaadin-ui-vaadinui-1  | Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
vaadin-ui-vaadinui-1  | 09:16:48.747 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereHandler com.vaadin.hilla.push.PushEndpoint mapped to context-path: /HILLA/push
vaadin-ui-vaadinui-1  | 09:16:48.749 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed the following AtmosphereInterceptor mapped to AtmosphereHandler com.vaadin.hilla.push.PushEndpoint
vaadin-ui-vaadinui-1  | 09:16:48.750 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.AtmosphereResourceLifecycleInterceptor : Atmosphere LifeCycle
vaadin-ui-vaadinui-1  | 09:16:48.750 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.client.TrackMessageSizeInterceptor :  Track Message Size Interceptor using |
vaadin-ui-vaadinui-1  | 09:16:48.750 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.SuspendTrackerInterceptor : UUID Tracking Interceptor
vaadin-ui-vaadinui-1  | 09:16:48.792 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing AtmosphereFramework
vaadin-ui-vaadinui-1  | 09:16:49.180 [main] INFO  o.h.t.services.TrackingDataService - Serializing Tokens
vaadin-ui-vaadinui-1  | 09:16:49.180 [main] INFO  o.h.t.services.TrackingDataService - Creating tokens file
vaadin-ui-vaadinui-1  | 09:16:49.180 [main] INFO  o.h.t.services.TrackingDataService - Created tokens parent directory
vaadin-ui-vaadinui-1  | 09:16:49.180 [main] INFO  o.h.t.services.TrackingDataService - Created tokens file
vaadin-ui-vaadinui-1  | 09:16:49.359 [main] ERROR o.h.t.services.SettingsService - Settings are null
vaadin-ui-vaadinui-1  | 09:16:50.065 [main] INFO  o.h.t.s.tracker.AniListAPIService - No AniList token set yet
vaadin-ui-vaadinui-1  | 09:16:50.668 [main] INFO  c.n.g.d.w.a.GraphiQLConfigurer - Configuring GraphiQL to use GraphQL endpoint at '/graphql'
vaadin-ui-vaadinui-1  | 09:16:51.561 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereHandler com.vaadin.flow.server.communication.PushAtmosphereHandler mapped to context-path: /*
vaadin-ui-vaadinui-1  | 09:16:51.561 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed the following AtmosphereInterceptor mapped to AtmosphereHandler com.vaadin.flow.server.communication.PushAtmosphereHandler
vaadin-ui-vaadinui-1  | 09:16:51.592 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Atmosphere is using org.atmosphere.util.VoidAnnotationProcessor for processing annotation
vaadin-ui-vaadinui-1  | 09:16:51.597 [main] INFO  org.atmosphere.util.ForkJoinPool - Using ForkJoinPool  java.util.concurrent.ForkJoinPool. Set the org.atmosphere.cpr.broadcaster.maxAsyncWriteThreads to -1 to fully use its power.
vaadin-ui-vaadinui-1  | 09:16:51.600 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol
vaadin-ui-vaadinui-1  | 09:16:51.604 [main] INFO  o.a.container.JSR356AsyncSupport - JSR 356 Mapping path /VAADIN/push
vaadin-ui-vaadinui-1  | 09:16:51.620 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installing Default AtmosphereInterceptors
vaadin-ui-vaadinui-1  | 09:16:51.621 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.CorsInterceptor : CORS Interceptor Support
vaadin-ui-vaadinui-1  | 09:16:51.621 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.CacheHeadersInterceptor : Default Response's Headers Interceptor
vaadin-ui-vaadinui-1  | 09:16:51.621 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.PaddingAtmosphereInterceptor : Browser Padding Interceptor Support
vaadin-ui-vaadinui-1  | 09:16:51.622 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.AndroidAtmosphereInterceptor : Android Interceptor Support
vaadin-ui-vaadinui-1  | 09:16:51.622 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.HeartbeatInterceptor : Heartbeat Interceptor Support
vaadin-ui-vaadinui-1  | 09:16:51.623 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.SSEAtmosphereInterceptor : SSE Interceptor Support
vaadin-ui-vaadinui-1  | 09:16:51.623 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.JSONPAtmosphereInterceptor : JSONP Interceptor Support
vaadin-ui-vaadinui-1  | 09:16:51.624 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.JavaScriptProtocol : Atmosphere JavaScript Protocol
vaadin-ui-vaadinui-1  | 09:16:51.624 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor : org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor
vaadin-ui-vaadinui-1  | 09:16:51.625 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.OnDisconnectInterceptor : Browser disconnection detection
vaadin-ui-vaadinui-1  | 09:16:51.625 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.IdleResourceInterceptor : org.atmosphere.interceptor.IdleResourceInterceptor
vaadin-ui-vaadinui-1  | 09:16:51.625 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Set org.atmosphere.cpr.AtmosphereInterceptor.disableDefaults to disable them.
vaadin-ui-vaadinui-1  | 09:16:51.625 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor CORS Interceptor Support with priority FIRST_BEFORE_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.631 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Default Response's Headers Interceptor with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.631 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Browser Padding Interceptor Support with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.631 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Android Interceptor Support with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.631 [main] INFO  o.a.interceptor.HeartbeatInterceptor - HeartbeatInterceptor configured with padding value 'X', client frequency 0 seconds and server frequency 60 seconds
vaadin-ui-vaadinui-1  | 09:16:51.631 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Heartbeat Interceptor Support with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.631 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor SSE Interceptor Support with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.631 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor JSONP Interceptor Support with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.632 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Atmosphere JavaScript Protocol with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.632 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.632 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Browser disconnection detection with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.632 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor org.atmosphere.interceptor.IdleResourceInterceptor with priority BEFORE_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.632 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Using EndpointMapper class org.atmosphere.util.DefaultEndpointMapper
vaadin-ui-vaadinui-1  | 09:16:51.632 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Using BroadcasterCache: org.atmosphere.cache.UUIDBroadcasterCache
vaadin-ui-vaadinui-1  | 09:16:51.632 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Default Broadcaster Class: org.atmosphere.cpr.DefaultBroadcaster
vaadin-ui-vaadinui-1  | 09:16:51.632 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Broadcaster Shared List Resources: false
vaadin-ui-vaadinui-1  | 09:16:51.632 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Broadcaster Polling Wait Time 100
vaadin-ui-vaadinui-1  | 09:16:51.632 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Shared ExecutorService supported: true
vaadin-ui-vaadinui-1  | 09:16:51.633 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Messaging ExecutorService Pool Size unavailable - Not instance of ThreadPoolExecutor
vaadin-ui-vaadinui-1  | 09:16:51.633 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Async I/O Thread Pool Size: 200
vaadin-ui-vaadinui-1  | 09:16:51.633 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
vaadin-ui-vaadinui-1  | 09:16:51.633 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Using AtmosphereResurceFactory: org.atmosphere.cpr.DefaultAtmosphereResourceFactory
vaadin-ui-vaadinui-1  | 09:16:51.633 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
vaadin-ui-vaadinui-1  | 09:16:51.636 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Invoke AtmosphereInterceptor on WebSocket message true
vaadin-ui-vaadinui-1  | 09:16:51.636 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - HttpSession supported: true
vaadin-ui-vaadinui-1  | 09:16:51.636 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Atmosphere is using DefaultAtmosphereObjectFactory for dependency injection and object creation
vaadin-ui-vaadinui-1  | 09:16:51.636 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Atmosphere is using async support: org.atmosphere.container.JSR356AsyncSupport running under container: Apache Tomcat/10.1.24 using jakarta.servlet/3.0 and jsr356/WebSocket API
vaadin-ui-vaadinui-1  | 09:16:51.637 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Atmosphere Framework 3.0.5.slf4jvaadin1 started.
vaadin-ui-vaadinui-1  | 09:16:51.639 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor  Track Message Size Interceptor using | with priority BEFORE_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.646 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-80"]
vaadin-ui-vaadinui-1  | 09:16:51.671 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Atmosphere is using org.atmosphere.cpr.DefaultAnnotationProcessor for processing annotation
vaadin-ui-vaadinui-1  | 09:16:51.671 [main] INFO  o.a.cpr.DefaultAnnotationProcessor - AnnotationProcessor class org.atmosphere.cpr.DefaultAnnotationProcessor$BytecodeBasedAnnotationProcessor being used
vaadin-ui-vaadinui-1  | 09:16:51.849 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Auto detecting WebSocketHandler in /WEB-INF/classes/
vaadin-ui-vaadinui-1  | 09:16:51.849 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol
vaadin-ui-vaadinui-1  | 09:16:51.849 [main] INFO  o.a.container.JSR356AsyncSupport - JSR 356 Mapping path /HILLA/push
vaadin-ui-vaadinui-1  | 09:16:51.851 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installing Default AtmosphereInterceptors
vaadin-ui-vaadinui-1  | 09:16:51.851 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.CorsInterceptor : CORS Interceptor Support
vaadin-ui-vaadinui-1  | 09:16:51.851 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.CacheHeadersInterceptor : Default Response's Headers Interceptor
vaadin-ui-vaadinui-1  | 09:16:51.851 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.PaddingAtmosphereInterceptor : Browser Padding Interceptor Support
vaadin-ui-vaadinui-1  | 09:16:51.851 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.AndroidAtmosphereInterceptor : Android Interceptor Support
vaadin-ui-vaadinui-1  | 09:16:51.851 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.HeartbeatInterceptor : Heartbeat Interceptor Support
vaadin-ui-vaadinui-1  | 09:16:51.851 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.SSEAtmosphereInterceptor : SSE Interceptor Support
vaadin-ui-vaadinui-1  | 09:16:51.851 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.JSONPAtmosphereInterceptor : JSONP Interceptor Support
vaadin-ui-vaadinui-1  | 09:16:51.851 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.JavaScriptProtocol : Atmosphere JavaScript Protocol
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor : org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.OnDisconnectInterceptor : Browser disconnection detection
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework -        org.atmosphere.interceptor.IdleResourceInterceptor : org.atmosphere.interceptor.IdleResourceInterceptor
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Set org.atmosphere.cpr.AtmosphereInterceptor.disableDefaults to disable them.
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor CORS Interceptor Support with priority FIRST_BEFORE_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Default Response's Headers Interceptor with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Browser Padding Interceptor Support with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Android Interceptor Support with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.a.interceptor.HeartbeatInterceptor - HeartbeatInterceptor configured with padding value 'X', client frequency 0 seconds and server frequency 60 seconds
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Heartbeat Interceptor Support with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor SSE Interceptor Support with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor JSONP Interceptor Support with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Atmosphere JavaScript Protocol with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Browser disconnection detection with priority AFTER_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.852 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor org.atmosphere.interceptor.IdleResourceInterceptor with priority BEFORE_DEFAULT
vaadin-ui-vaadinui-1  | 09:16:51.853 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Using EndpointMapper class org.atmosphere.util.DefaultEndpointMapper
vaadin-ui-vaadinui-1  | 09:16:51.853 [main] WARN  o.atmosphere.cpr.AtmosphereFramework - No BroadcasterCache configured. Broadcasted message between client reconnection will be LOST. It is recommended to configure the org.atmosphere.cache.UUIDBroadcasterCache
vaadin-ui-vaadinui-1  | 09:16:51.853 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Default Broadcaster Class: org.atmosphere.util.SimpleBroadcaster
vaadin-ui-vaadinui-1  | 09:16:51.853 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Broadcaster Shared List Resources: false
vaadin-ui-vaadinui-1  | 09:16:51.853 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Broadcaster Polling Wait Time 100
vaadin-ui-vaadinui-1  | 09:16:51.853 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Shared ExecutorService supported: true
vaadin-ui-vaadinui-1  | 09:16:51.853 [main] INFO  org.atmosphere.util.ForkJoinPool - Using ForkJoinPool  java.util.concurrent.ForkJoinPool. Set the org.atmosphere.cpr.broadcaster.maxAsyncWriteThreads to -1 to fully use its power.
vaadin-ui-vaadinui-1  | 09:16:51.853 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Messaging ExecutorService Pool Size unavailable - Not instance of ThreadPoolExecutor
vaadin-ui-vaadinui-1  | 09:16:51.854 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Async I/O Thread Pool Size: 200
vaadin-ui-vaadinui-1  | 09:16:51.854 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
vaadin-ui-vaadinui-1  | 09:16:51.854 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Using AtmosphereResurceFactory: org.atmosphere.cpr.DefaultAtmosphereResourceFactory
vaadin-ui-vaadinui-1  | 09:16:51.854 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
vaadin-ui-vaadinui-1  | 09:16:51.854 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Invoke AtmosphereInterceptor on WebSocket message true
vaadin-ui-vaadinui-1  | 09:16:51.854 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - HttpSession supported: false
vaadin-ui-vaadinui-1  | 09:16:51.854 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Atmosphere is using DefaultAtmosphereObjectFactory for dependency injection and object creation
vaadin-ui-vaadinui-1  | 09:16:51.854 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Atmosphere is using async support: org.atmosphere.container.JSR356AsyncSupport running under container: Apache Tomcat/10.1.24 using jakarta.servlet/3.0 and jsr356/WebSocket API
vaadin-ui-vaadinui-1  | 09:16:51.854 [main] INFO  o.atmosphere.cpr.AtmosphereFramework - Atmosphere Framework 3.0.5.slf4jvaadin1 started.
vaadin-ui-vaadinui-1  | 09:16:51.883 [main] INFO  c.v.f.s.DefaultDeploymentConfiguration - Vaadin is running in production mode.
vaadin-ui-vaadinui-1  |
vaadin-ui-vaadinui-1  | The following feature previews are enabled:
vaadin-ui-vaadinui-1  | - Server side WebPush API
vaadin-ui-vaadinui-1  |
vaadin-ui-vaadinui-1  |
vaadin-ui-vaadinui-1  | 09:16:51.915 [main] INFO  c.v.flow.spring.SpringInstantiator - The number of beans implementing 'I18NProvider' is 0. Cannot use Spring beans for I18N, falling back to the default behavior
vaadin-ui-vaadinui-1  | 09:16:51.962 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port 80 (http) with context path '/'
vaadin-ui-vaadinui-1  | 09:16:51.993 [main] INFO  o.h.t.TachideskVaadinUiApplication - Started TachideskVaadinUiApplication in 7.185 seconds (process running for 8.287)
vaadin-ui-vaadinui-1  | 09:16:52.048 [main] ERROR o.s.boot.SpringApplication - Application run failed
vaadin-ui-vaadinui-1  | java.lang.reflect.UndeclaredThrowableException: Failed to invoke event listener method
vaadin-ui-vaadinui-1  | HandlerMethod details:
vaadin-ui-vaadinui-1  | Bean [online.hatsunemiku.tachideskvaadinui.startup.TrayHandler]
vaadin-ui-vaadinui-1  | Method [public void online.hatsunemiku.tachideskvaadinui.startup.TrayHandler.registerTray()]
vaadin-ui-vaadinui-1  | Resolved arguments:
vaadin-ui-vaadinui-1  |
vaadin-ui-vaadinui-1  |         at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:382)
vaadin-ui-vaadinui-1  |         at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:237)
vaadin-ui-vaadinui-1  |         at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:168)
vaadin-ui-vaadinui-1  |         at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
vaadin-ui-vaadinui-1  |         at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
vaadin-ui-vaadinui-1  |         at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
vaadin-ui-vaadinui-1  |         at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451)
vaadin-ui-vaadinui-1  |         at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:103)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:76)
vaadin-ui-vaadinui-1  |         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:76)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.SpringApplication.run(SpringApplication.java:341)
vaadin-ui-vaadinui-1  |         at online.hatsunemiku.tachideskvaadinui.TachideskVaadinUiApplication.main(TachideskVaadinUiApplication.java:26)
vaadin-ui-vaadinui-1  |         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
vaadin-ui-vaadinui-1  |         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
vaadin-ui-vaadinui-1  |         at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
vaadin-ui-vaadinui-1  | Caused by: java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
vaadin-ui-vaadinui-1  |         at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
vaadin-ui-vaadinui-1  |         at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:105)
vaadin-ui-vaadinui-1  |         at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
vaadin-ui-vaadinui-1  |         at java.desktop/sun.awt.X11GraphicsEnvironment.initStatic(X11GraphicsEnvironment.java:64)
vaadin-ui-vaadinui-1  |         at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:59)
vaadin-ui-vaadinui-1  |         at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:37)
vaadin-ui-vaadinui-1  |         at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:91)
vaadin-ui-vaadinui-1  |         at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:82)
vaadin-ui-vaadinui-1  |         at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:104)
vaadin-ui-vaadinui-1  |         at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:225)
vaadin-ui-vaadinui-1  |         at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:41)
vaadin-ui-vaadinui-1  |         at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:595)
vaadin-ui-vaadinui-1  |         at java.desktop/java.awt.SystemTray.isSupported(SystemTray.java:213)
vaadin-ui-vaadinui-1  |         at online.hatsunemiku.tachideskvaadinui.startup.TrayHandler.registerTray(TrayHandler.java:41)
vaadin-ui-vaadinui-1  |         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
vaadin-ui-vaadinui-1  |         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
vaadin-ui-vaadinui-1  |         at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:365)
vaadin-ui-vaadinui-1  |         ... 20 common frames omitted
vaadin-ui-vaadinui-1  | 09:16:52.051 [main] INFO  o.h.t.services.SettingsService - Saving settings
vaadin-ui-vaadinui-1  | 09:16:52.075 [main] INFO  o.h.t.startup.TachideskStarter - Stopping Jar
vaadin-ui-vaadinui-1  | 09:16:52.078 [main] INFO  o.h.t.services.TrackingDataService - Serializing Tokens
vaadin-ui-vaadinui-1  | 09:16:52.079 [main] INFO  o.h.t.services.TrackingDataService - Serializing Trackers
vaadin-ui-vaadinui-1 exited with code 1
```

I

**Comment by RhanCandia** [comment]
I didn't see any reference to the headless mode in the logs. The tomcat port was changed to 80 so the -Dserver.port=80 argument worked. But not the -Dvaaui.headless=true.

**Comment by aless2003** [comment]
Hmm, you sure you changed the branch? Headless mode should log it's state before spring inits, but there's nothing there at all. Only way I can imagine that happening if it's still master branch rather than the headless branch

**Comment by RhanCandia** [comment]
> Hmm, you sure you changed the branch? Headless mode should log it's state before spring inits, but there's nothing there at all. Only way I can imagine that happening if it's still master branch rather than the headless branch

Okay, came back to say it but you already noticed. I didn't notice it was still building in master. Now I switched to the headless branch and it does work now. I'm sorry for the confusion.

**Comment by aless2003** [comment]
Eh it's fine, good to know it works, I'll leave this open until it's merged. Have fun with the manga reading 😊

**Comment by aless2003** [comment]
Merged, the next release will include this (not sure when that one is coming out yet though)
